general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/asmk/Pictures/Wallpapers/votre_fond.jpg   # Mets le chemin de ton wallpaper actuel
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3 # 0 déconnecte le flou
    blur_size = 7
}

label {
    monitor =
    text = $TIME
    color = rgba(189, 147, 249, 1.0) # Ton Mauve
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(189, 147, 249, 1.0) # Bordure Mauve
    inner_color = rgba(30, 30, 46, 0.7)    # Fond translucide
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Mot de passe...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}
