background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 20%, 5%
    rounding = 15
    inner_color = rgba(0, 0, 0, 0.4)
    outer_color = rgba(200, 200, 200, 1.0)
    font_color = rgb(230, 230, 230)
    placeholder_text = <i>Mot de passe…</i>
    halign = center
    valign = center
}

