# Variables NVIDIA
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1
env = XWAYLAND_NO_GLAMOR,1
env = WLR_NO_HARDWARE_CURSORS,1
env = __GL_MaxFramesAllowed,1

# Debug
debug {
    damage_tracking = 0
}

# Opengl
opengl {
    nvidia_anti_flicker = false
}

